pod 'FBSDKCoreKit', '~> 4.6'
pod 'SDWebImage', '~> 3.7.2'

pod 'RSKImageCropper', :git => 'https://github.com/andrew804/RSKImageCropper.git'
#pod 'RSKImageCropper', :path => '~/Desktop/RSKImageCropper'
