pod 'Facebook-iOS-SDK', '~> 4.0'
pod 'SDWebImage', '~> 3.7.2'

pod 'RSKImageCropper', :git => 'https://github.com/andrew804/RSKImageCropper.git'
#pod 'RSKImageCropper', :path => '~/Desktop/RSKImageCropper'
